"""Generate Chinese TTS voiceover for every scene in src/data/script.ts.

Uses Microsoft Edge TTS (free, no API key, decent neural Mandarin
voice).  Requires: pip install edge-tts

Output:
  public/audio/scene_01.mp3 ... scene_14.mp3
  src/data/audio-manifest.ts (regenerated)

Usage:
  cd promo_video
  python scripts/generate-tts.py
"""
from __future__ import annotations

import asyncio
import json
import re
import sys
from pathlib import Path

try:
    import edge_tts
except ImportError:
    print("ERROR: pip install edge-tts", file=sys.stderr)
    sys.exit(1)

ROOT = Path(__file__).resolve().parent.parent
SCRIPT_TS = ROOT / "src" / "data" / "script.ts"
AUDIO_DIR = ROOT / "public" / "audio"
MANIFEST_TS = ROOT / "src" / "data" / "audio-manifest.ts"

# Taiwanese-accent female neural voice; switch to zh-CN-XiaoxiaoNeural
# for mainland accent, or zh-TW-YunJheNeural for male.
VOICE = "zh-TW-HsiaoChenNeural"
RATE = "+0%"      # speak rate; "-10%" / "+15%" etc. if needed
PITCH = "+0Hz"


def extract_scenes(ts_source: str) -> list[tuple[int, str]]:
    """Yank scene id + vo_zh lines from script.ts using regex.

    Avoids needing a real TS parser; the script.ts format is structured
    enough that regex is reliable for now.
    """
    out: list[tuple[int, str]] = []
    # Match: id: <num>, ... vo_zh: '<content with maybe concatenated strings>'
    # Each scene block ends at the next "{ id:" or end of array.
    block_re = re.compile(
        r"\{\s*id:\s*(\d+),.*?vo_zh:\s*([^,}]+(?:,\s*'[^']*'\s*\+?)*)",
        re.DOTALL,
    )
    for m in block_re.finditer(ts_source):
        scene_id = int(m.group(1))
        vo_block = m.group(2)
        # Re-join concatenated string literals: '...' + '...' + '...'
        parts = re.findall(r"'([^']*)'", vo_block)
        text = "".join(parts).strip()
        if text:
            out.append((scene_id, text))
    return out


async def synth(scene_id: int, text: str, out_path: Path) -> None:
    print(f"  [{scene_id:02d}] {text[:40]}{'...' if len(text) > 40 else ''}")
    communicate = edge_tts.Communicate(
        text=text, voice=VOICE, rate=RATE, pitch=PITCH,
    )
    await communicate.save(str(out_path))


async def main() -> int:
    if not SCRIPT_TS.exists():
        print(f"ERROR: {SCRIPT_TS} not found")
        return 1
    AUDIO_DIR.mkdir(parents=True, exist_ok=True)

    scenes = extract_scenes(SCRIPT_TS.read_text(encoding="utf-8"))
    if not scenes:
        print("ERROR: no scenes parsed from script.ts")
        return 1
    print(f"Found {len(scenes)} scenes with VO text.")
    print(f"Voice: {VOICE}")
    print(f"Output: {AUDIO_DIR}/")
    print()

    generated: list[int] = []
    for scene_id, text in scenes:
        out_path = AUDIO_DIR / f"scene_{scene_id:02d}.mp3"
        try:
            await synth(scene_id, text, out_path)
            generated.append(scene_id)
        except Exception as e:
            print(f"  [{scene_id:02d}] FAIL: {e}")

    # Regenerate audio-manifest.ts
    manifest_content = (
        '/**\n'
        ' * Audio availability manifest — regenerated by '
        'scripts/generate-tts.py.\n'
        ' * Lists scene IDs whose voiceover mp3 file is present.\n'
        ' * Composition.tsx reads this to decide whether to mount '
        '<Audio>.\n'
        ' */\n'
        'export const AUDIO_AVAILABLE: ReadonlySet<number> = new Set('
        + json.dumps(sorted(generated))
        + ');\n'
    )
    MANIFEST_TS.write_text(manifest_content, encoding="utf-8")
    print()
    print(f"OK: generated {len(generated)}/{len(scenes)} mp3 files")
    print(f"Updated: {MANIFEST_TS.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(asyncio.run(main()))
