# -*- coding: utf-8 -*-
"""Which cells belong in `home_regime`? — TODO §0.59b.

Product side asked (產品端詢問_主場定義是否納入TREND_DOWN_20260826.md) why
§0.59's filter keeps only RANGING when TREND_DOWN's forward meanR is higher.
They refused to change it themselves and asked for a ruling. Correct call.

THE HONEST BACKGROUND, stated first because it changes who bears the burden
of proof: §0.59 was generated by the §0.58 decomposition, whose criterion
was "which cells held between two non-overlapping samples". Applied to the
table it produced, that criterion selects TWO cells, not one. RANGING-only
was a carry-over from the UNDIRECTED framing of the survival layer (§0.49:
ADX RANGING vs TRENDING) — the very simplification §0.54b already overturned
on this line. So this is not a post-hoc widening on new evidence; it is the
original criterion applied without the leftover.

Consequently the numbers in the product side's t-table are NOT used to
decide. They were computed after looking at the forward sample; leaning on
them would be exactly the C/D trap. The decision runs on §0.58's two-sample
consistency, which predates that table.

CRITERION, frozen before running (a cell joins home_regime iff ALL hold):
  C1  meanR > 0 in BOTH non-overlapping samples (backtest pre-FREEZE and
      forward post-FREEZE). Sign consistency across independent samples is
      the whole basis of §0.58's reading; nothing weaker qualifies.
  C2  per-coin breadth >= 5/9 in the BACKTEST sample. Breadth is only
      demanded of the large sample — the forward one is too thin to carry
      it, and demanding it there would silently select on noise.
  C3  day-clustered CI low > 0 in the BACKTEST sample. Same reasoning: the
      forward sample cannot support an interval test, so it is not asked to.

FALSIFICATION, also pre-stated. If TREND_DOWN passes C1-C3 its forward
result must additionally not be an artefact of one coin or a few days:
  F1  no single coin contributes > 50% of the forward cell's total R
  F2  no single UTC day contributes > 50% of it
A cell that passes C1-C3 but fails F1/F2 is reported as PASSES-BUT-FRAGILE
and the ruling says so rather than hiding it.

SENSITIVITY is reported unconditionally: what the union's forward meanR
would be if the added cell were truly worth zero. If the union still beats
a plausible alternative under that assumption, the decision is robust to
being wrong about the added cell — which matters more than the point
estimate, because n is small.

Read-only. Decides a DEFINITION, scores no gate.
"""
from __future__ import annotations

import csv
import json
import random
import statistics as st
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "research" / "sweep_failure"))
try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:
    pass

import sweep_core as SC                                    # noqa: E402
from research.crowd_battery2 import adx_state              # noqa: E402

CACHE = ROOT / "research" / "sweep_failure" / ".cache"
LOG = ROOT / "research" / "results" / "sweep_shadow_log.csv"
OUT = ROOT / "research" / "results" / "raid_home_regime_def.json"
CORE9 = ["BTC", "ETH", "SOL", "BNB", "XRP", "DOGE", "ADA", "LINK", "AVAX"]
PIERCE_B = 0.25
FREEZE = int(datetime(2026, 7, 28, tzinfo=timezone.utc).timestamp())
LB = 24
CELLS = ("RANGING", "TREND_DOWN", "NEUTRAL", "TREND_UP")
random.seed(11)


def cell_of(lab, ret24):
    if lab == "RANGING":
        return "RANGING"
    if lab != "TRENDING":
        return "NEUTRAL"
    return "TREND_UP" if ret24 > 0 else "TREND_DOWN"


def clustered_ci(pairs, n_boot=4000):
    """Day-clustered bootstrap CI of the mean. pairs = [(day, R), ...]."""
    if not pairs:
        return None
    by_day = defaultdict(list)
    for d, r in pairs:
        by_day[d].append(r)
    days = list(by_day)
    if len(days) < 3:
        return None
    means = []
    for _ in range(n_boot):
        pick = [random.choice(days) for _ in days]
        vals = [x for d in pick for x in by_day[d]]
        if vals:
            means.append(st.mean(vals))
    means.sort()
    return means[int(0.025 * len(means))], means[int(0.975 * len(means))]


def load():
    hist = {c: [] for c in CELLS}       # (day, R, sym)
    fwd = {c: [] for c in CELLS}
    labs, rets = {}, {}
    for sym in CORE9:
        fp = CACHE / f"{sym}USDT_1h.csv"
        if not fp.exists():
            continue
        bars = SC.load_csv(str(fp))
        c = [b[SC.C] for b in bars]
        adx = adx_state(bars)
        labs[sym] = adx
        rets[sym] = {bars[i][0]: c[i] / c[i - LB] - 1
                     for i in range(LB, len(bars))}
        for fill_ts, _x, R, _l, _A, _s, pierce, _sd in SC.backtest_symbol(bars):
            if pierce > PIERCE_B or int(fill_ts) >= FREEZE:
                continue
            h = int(fill_ts) // 3600 * 3600
            lab = adx.get(h)
            if lab is None or h not in rets[sym]:
                continue
            hist[cell_of(lab, rets[sym][h])].append((h // 86400, R, sym))

    with open(LOG, newline="", encoding="utf-8-sig") as fh:
        for r in csv.DictReader(fh):
            if (r.get("status") != "CLOSED" or r.get("variant_b") != "1"
                    or r.get("universe") != "core9"):
                continue
            sym = r["symbol"]
            if sym not in labs:
                continue
            try:
                ts, R = int(float(r["fill_ts"])), float(r["net_r"])
            except (ValueError, TypeError):
                continue
            h = ts // 3600 * 3600
            lab = labs[sym].get(h)
            if lab is None or h not in rets[sym]:
                continue
            fwd[cell_of(lab, rets[sym][h])].append((h // 86400, R, sym))
    return hist, fwd


def main() -> int:
    hist, fwd = load()
    print("§0.59b  home_regime 的成員資格 —— 判準先於數字\n")
    print("C1 兩樣本 meanR 皆 > 0 ∧ C2 回測逐幣 ≥5/9 ∧ C3 回測日聚類 CI 下緣 > 0\n")

    print(f"{'cell':11} {'回測 n':>7} {'回測 R':>9} {'廣度':>7} "
          f"{'回測 CI':>18} {'前瞻 n':>7} {'前瞻 R':>9}  判定")
    res, members = {}, []
    for cell in CELLS:
        hv, fv = hist[cell], fwd[cell]
        if not hv or not fv:
            continue
        hm, fm = st.mean([x[1] for x in hv]), st.mean([x[1] for x in fv])
        per = defaultdict(list)
        for _d, R, s in hv:
            per[s].append(R)
        breadth = sum(1 for s in per if st.mean(per[s]) > 0)
        ci = clustered_ci([(d, R) for d, R, _s in hv])
        c1 = hm > 0 and fm > 0
        c2 = breadth >= 5
        c3 = ci is not None and ci[0] > 0
        ok = c1 and c2 and c3
        if ok:
            members.append(cell)
        cis = f"[{ci[0]:+.3f},{ci[1]:+.3f}]" if ci else "—"
        flag = "".join("✓" if x else "✗" for x in (c1, c2, c3))
        print(f"{cell:11} {len(hv):7d} {hm:+9.4f} {breadth:5d}/9 {cis:>18} "
              f"{len(fv):7d} {fm:+9.4f}  {flag} {'納入' if ok else '排除'}")
        res[cell] = {"hist_n": len(hv), "hist_R": round(hm, 4),
                     "breadth": f"{breadth}/9",
                     "hist_ci": [round(ci[0], 4), round(ci[1], 4)] if ci else None,
                     "fwd_n": len(fv), "fwd_R": round(fm, 4),
                     "C1": c1, "C2": c2, "C3": c3, "member": ok}

    print(f"\n  → 判準選出的主場：{' ∪ '.join(members)}")

    # ── falsification on any cell beyond RANGING ───────────────────────
    print("\n── 反證關（只對 RANGING 以外的新成員）──")
    fragile = []
    for cell in members:
        if cell == "RANGING":
            continue
        fv = fwd[cell]
        tot = sum(x[1] for x in fv)
        by_c, by_d = defaultdict(float), defaultdict(float)
        for d, R, s in fv:
            by_c[s] += R
            by_d[d] += R
        top_c = max(by_c.items(), key=lambda kv: abs(kv[1]))
        top_d = max(by_d.items(), key=lambda kv: abs(kv[1]))
        fc = top_c[1] / tot if tot else 0
        fd = top_d[1] / tot if tot else 0
        f1, f2 = fc <= 0.5, fd <= 0.5
        print(f"  {cell}: 前瞻總 R {tot:+.3f}｜最大單幣 {top_c[0]} "
              f"{top_c[1]:+.3f} ({100*fc:.0f}%) {'✓' if f1 else '✗'}"
              f"｜最大單日 {top_d[1]:+.3f} ({100*fd:.0f}%) {'✓' if f2 else '✗'}")
        pos_c = sum(1 for s in by_c if by_c[s] > 0)
        print(f"      前瞻逐幣為正 {pos_c}/{len(by_c)}")
        if not (f1 and f2):
            fragile.append(cell)
        res[cell]["fwd_top_coin_share"] = round(fc, 3)
        res[cell]["fwd_top_day_share"] = round(fd, 3)
        res[cell]["fragile"] = not (f1 and f2)

    # ── what the definition change actually buys, on forward data ──────
    print("\n── 定義變更在前瞻樣本上的後果 ──")
    nf_all = sum(len(fwd[c]) for c in CELLS)
    opts = {"RANGING 單格（現行規格）": ["RANGING"],
            f"{' ∪ '.join(members)}（判準選出）": members,
            "不濾（全體）": list(CELLS)}
    summ = {}
    for name, ms in opts.items():
        vals = [x[1] for c in ms for x in fwd[c]]
        m = st.mean(vals) if vals else 0
        ci = clustered_ci([(d, R) for c in ms for d, R, _s in fwd[c]])
        cis = f"[{ci[0]:+.3f},{ci[1]:+.3f}]" if ci else "—"
        print(f"  {name:32} n={len(vals):<4} meanR {m:+.4f}  "
              f"CI {cis:<18} 訊號量 {100*len(vals)/nf_all:.0f}%")
        summ[name] = {"n": len(vals), "meanR": round(m, 4),
                      "ci": [round(ci[0], 4), round(ci[1], 4)] if ci else None,
                      "share": round(len(vals) / nf_all, 3)}

    # ── sensitivity: added cells assumed to be worth exactly zero ───────
    added = [c for c in members if c != "RANGING"]
    if added:
        nr = len(fwd["RANGING"])
        na = sum(len(fwd[c]) for c in added)
        base = st.mean([x[1] for x in fwd["RANGING"]])
        worst = base * nr / (nr + na)
        print(f"\n── 敏感度：假設 {'/'.join(added)} 的真實值是 0 ──")
        print(f"  聯集 meanR 會從 {summ[list(opts)[1]]['meanR']:+.4f} "
              f"退到 {worst:+.4f}（RANGING 單格是 {base:+.4f}）")
        print(f"  → 代價 {worst - base:+.4f}R，換到 +{100*na/nr:.0f}% 的訊號量")
        res["sensitivity"] = {"union_if_added_worth_zero": round(worst, 4),
                              "ranging_only": round(base, 4),
                              "extra_signal_pct": round(100 * na / nr, 1)}

    verdict = (f"home_regime = {' ∪ '.join(members)}"
               + ("（新成員通過反證關）" if not fragile
                  else f"，但 {'/'.join(fragile)} 標記 FRAGILE"))
    print(f"\n裁示：{verdict}")
    res["members"] = members
    res["fragile"] = fragile
    res["forward_options"] = summ
    res["verdict"] = verdict
    OUT.write_text(json.dumps(res, indent=1, ensure_ascii=False),
                   encoding="utf-8")
    print(f"\nwritten {OUT.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
