/**
 * Audio availability manifest — regenerated by scripts/generate-tts.py.
 * Lists scene IDs whose voiceover mp3 file is present.
 * Composition.tsx reads this to decide whether to mount <Audio>.
 */
export const AUDIO_AVAILABLE: ReadonlySet<number> = new Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]);
