import React from 'react';
import {AbsoluteFill, Sequence, staticFile, Audio} from 'remotion';
import {SCENES} from './data/script';
import {AUDIO_AVAILABLE} from './data/audio-manifest';
import {Subtitles} from './components/Subtitles';
import {Scene01ColdOpen} from './scenes/Scene01ColdOpen';
import {Scene02Hook} from './scenes/Scene02Hook';
import {Scene03Problem} from './scenes/Scene03Problem';
import {Scene04Architecture} from './scenes/Scene04Architecture';
import {SceneStub} from './scenes/SceneStub';

const SCENE_COMPONENTS: Record<number, React.FC> = {
  1: Scene01ColdOpen,
  2: Scene02Hook,
  3: Scene03Problem,
  4: Scene04Architecture,
  // 5–14 fall through to SceneStub.
};

const audioPath = (id: number) =>
  staticFile(`audio/scene_${String(id).padStart(2, '0')}.mp3`);

export const PromoVideo: React.FC = () => {
  return (
    <AbsoluteFill style={{backgroundColor: '#0a0e1a'}}>
      {SCENES.map((scene) => {
        const Comp = SCENE_COMPONENTS[scene.id] ?? SceneStub;
        // Only mount <Audio> if the mp3 actually exists at bundle time —
        // Remotion's renderer treats missing assets as fatal.  The
        // audio-manifest.ts is regenerated by scripts/generate-tts.ts
        // after each TTS run.
        const hasAudio = AUDIO_AVAILABLE.has(scene.id);
        return (
          <Sequence
            key={scene.id}
            from={scene.start}
            durationInFrames={scene.end - scene.start}
            name={`Scene ${scene.id}: ${scene.title}`}
          >
            <Comp />
            {hasAudio && (
              <Audio src={audioPath(scene.id)} volume={1} />
            )}
          </Sequence>
        );
      })}
      <Subtitles />
    </AbsoluteFill>
  );
};
