#!/usr/bin/env bash
# Install pre-commit secret scanner into .git/hooks/pre-commit.
#
# Run once after clone (and after any time .git/hooks is wiped).
# Hooks are NOT versioned, so each clone needs this run.

set -e

REPO_ROOT="$(git rev-parse --show-toplevel)"
HOOK="${REPO_ROOT}/.git/hooks/pre-commit"
SCANNER="${REPO_ROOT}/scripts/pre_commit_secret_scan.py"

if [ ! -f "$SCANNER" ]; then
    echo "ERROR: scanner not found at $SCANNER"
    exit 1
fi

cat > "$HOOK" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install_security_hooks.sh
# Edit the source script, not this file.
REPO_ROOT="$(git rev-parse --show-toplevel)"
exec python3 "${REPO_ROOT}/scripts/pre_commit_secret_scan.py"
EOF

chmod +x "$HOOK"
chmod +x "$SCANNER"

echo "pre-commit hook installed: $HOOK"
echo
echo "Quick self-test (should pass on a clean repo):"
python3 "$SCANNER" && echo "OK" || echo "FAIL — review output above"
