"""OKX WebSocket private channel client (orders / positions / balance).

Connection-resilience + message parsers complete (2026-05-28).
Reconnect strategy:
  - Exponential backoff: 1s, 2s, 4s, 8s, 16s (cap 30s)
  - Per docs: 3 consecutive fails → trigger A2 (demote)
  - On reconnect: re-auth + re-subscribe + REST cross-check (to fill
    any events missed during disconnect)

Heartbeat:
  - OKX sends ping/pong on its own.  We additionally send a manual
    ping every 25s (OKX server-side timeout is 30s).  We track
    last_msg_received_ts (any message resets it) for heartbeat age.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import logging
import threading
import time
from collections import deque
from datetime import datetime, timezone
from typing import Callable, Optional

import websocket  # websocket-client per CLAUDE.md coding rules

from indicator.okx.config import OkxConfig
from indicator.okx.types import (
    BalanceEvent, ConnectivityStatus, OrderEvent, PositionEvent,
)

logger = logging.getLogger(__name__)


# Type aliases for callbacks
OrderCallback = Callable[[OrderEvent], None]
PositionCallback = Callable[[PositionEvent], None]
BalanceCallback = Callable[[BalanceEvent], None]


# ── Wire-format parsers ────────────────────────────────────────────────

def _parse_optional_float(value) -> Optional[float]:
    """OKX often sends empty strings instead of nulls.  Treat both as None."""
    if value is None or value == "":
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def _parse_ts_ms(value) -> Optional[datetime]:
    """Decode OKX uTime millisecond-epoch string into UTC datetime."""
    if value is None or value == "":
        return None
    try:
        ms = int(value)
    except (TypeError, ValueError):
        return None
    return datetime.fromtimestamp(ms / 1000.0, tz=timezone.utc)


def _parse_order_event(item: dict) -> OrderEvent:
    """Decode OKX 'orders' channel item → OrderEvent.

    OKX wire format:
      ordId, clOrdId, state (live/partially_filled/filled/canceled),
      fillPx, fillSz (last-fill size, "" if no fill),
      accFillSz (cumulative), fee (signed, negative when user pays),
      uTime (ms epoch as string).
      algoClOrdId / algoId: present when this fill was generated by an
        algo trigger (e.g. trail-stop firing).  clOrdId may be empty
        in that case, so consumers matching on stop_algo_cl_ord_id
        MUST check algo_cl_ord_id, not clOrdId.
    """
    fill_px = _parse_optional_float(item.get("fillPx"))
    fill_sz_raw = _parse_optional_float(item.get("fillSz"))
    # fractional fills allowed (OKX lotSz 0.01) — keep as float, no int() truncation
    fill_sz: Optional[float] = fill_sz_raw
    fee = _parse_optional_float(item.get("fee"))
    return OrderEvent(
        cl_ord_id=item.get("clOrdId", "") or "",
        ord_id=item.get("ordId", "") or "",
        state=item.get("state", "unknown") or "unknown",
        fill_price=fill_px,
        fill_size=fill_sz,
        fee_usd=fee,
        ts=_parse_ts_ms(item.get("uTime")),
        algo_cl_ord_id=item.get("algoClOrdId", "") or "",
        algo_id=item.get("algoId", "") or "",
        raw=item,
    )


def _parse_position_event(item: dict) -> PositionEvent:
    """Decode OKX 'positions' channel item → PositionEvent.

    pos is signed in net_mode; direction inferred upstream.
    """
    return PositionEvent(
        inst_id=item.get("instId", "") or "",
        pos=_parse_optional_float(item.get("pos")) or 0.0,
        avg_price=_parse_optional_float(item.get("avgPx")) or 0.0,
        ts=_parse_ts_ms(item.get("uTime")),
        raw=item,
    )


def _parse_balance_event(item: dict) -> BalanceEvent:
    """Decode OKX 'account' channel item → BalanceEvent.

    Pulls USDT available balance from details[] (multi-ccy account).
    """
    total_eq = _parse_optional_float(item.get("totalEq")) or 0.0
    available = 0.0
    for ccy_row in item.get("details") or []:
        if (ccy_row.get("ccy") or "").upper() == "USDT":
            available = _parse_optional_float(ccy_row.get("availBal")) or 0.0
            break
    return BalanceEvent(
        total_eq_usd=total_eq,
        available_usd=available,
        ts=_parse_ts_ms(item.get("uTime")),
        raw=item,
    )


class OkxWsPrivateClient:
    """OKX private WS — order / position / balance push channels.

    All WS message handling runs in a background daemon thread.  Callbacks
    fire on that thread; consumers must do their own DB persistence
    (don't keep state in memory — see okx_integration_design.md §6).
    """

    PING_INTERVAL_SEC = 25.0
    BACKOFF_SEC = [1, 2, 4, 8, 16, 30]   # cap 30s

    def __init__(self, cfg: OkxConfig):
        self._cfg = cfg
        self._ws: Optional[websocket.WebSocketApp] = None
        self._ws_thread: Optional[threading.Thread] = None
        self._stop_evt = threading.Event()
        self._lock = threading.Lock()

        # ── State (read by check_connectivity)
        self._connected: bool = False
        self._authenticated: bool = False
        # Seed with construction time (NOT 0): a fresh WS that hasn't received
        # its first message yet should report a SMALL heartbeat age (still
        # connecting), not the 999 sentinel that instantly trips A1 DEMOTE on
        # every restart.  A genuinely dead WS still grows age past the 300s
        # A1 threshold within ~5 min, so real disconnects are still caught.
        self._last_msg_ts: float = time.time()
        self._consecutive_reconnect_fails: int = 0
        self._last_reconnect_ts: Optional[datetime] = None
        self._subscribed_channels: set[str] = set()
        # ── Diagnostic state (read by /okx-status)
        self._last_error: Optional[str] = None
        self._auth_count: int = 0          # total successful auths
        self._connect_count: int = 0       # total connect attempts
        self._session_authed: bool = False  # auth status for current session
        # Per-session breadcrumbs (overwritten each connect)
        self._last_session_opened: bool = False
        self._last_session_login_sent: bool = False
        self._last_session_msgs_received: int = 0
        self._last_session_close_code: Optional[int] = None
        self._last_session_close_msg: Optional[str] = None
        self._last_session_last_msg: Optional[str] = None  # first 200 chars
        self._last_ws_error: Optional[str] = None

        # ── Callbacks (set by consumer)
        self._on_order: Optional[OrderCallback] = None
        self._on_position: Optional[PositionCallback] = None
        self._on_balance: Optional[BalanceCallback] = None

    # ── Public API ─────────────────────────────────────────────────────

    def start(self) -> None:
        """Start the WS thread.  Returns immediately; connection is async."""
        if self._ws_thread and self._ws_thread.is_alive():
            return
        self._stop_evt.clear()
        self._ws_thread = threading.Thread(
            target=self._run_loop, name="okx-ws-private", daemon=True,
        )
        self._ws_thread.start()
        # Also start a manual ping thread
        threading.Thread(target=self._ping_loop, name="okx-ws-ping",
                         daemon=True).start()

    def stop(self) -> None:
        self._stop_evt.set()
        with self._lock:
            ws = self._ws
        if ws is not None:
            try:
                ws.close()
            except Exception:
                pass

    def subscribe_orders(self, callback: OrderCallback) -> None:
        self._on_order = callback
        self._subscribed_channels.add("orders")
        self._try_subscribe(["orders"])

    def subscribe_positions(self, callback: PositionCallback) -> None:
        self._on_position = callback
        self._subscribed_channels.add("positions")
        self._try_subscribe(["positions"])

    def subscribe_balance(self, callback: BalanceCallback) -> None:
        self._on_balance = callback
        self._subscribed_channels.add("account")
        self._try_subscribe(["account"])

    def connectivity(self) -> ConnectivityStatus:
        now = time.time()
        age = now - self._last_msg_ts if self._last_msg_ts > 0 else 999.0
        return ConnectivityStatus(
            public_ws_ok=False,                # other client handles public
            private_ws_ok=self._connected and self._authenticated,
            last_public_heartbeat_age_sec=999.0,
            last_private_heartbeat_age_sec=age,
            rest_last_latency_ms=None,
            rest_circuit_tripped=False,
            last_reconnect_ts=self._last_reconnect_ts,
            consecutive_reconnect_fails=self._consecutive_reconnect_fails,
        )

    def diag_state(self) -> dict:
        """Diagnostic snapshot for /okx-status; not used by executor."""
        now = time.time()
        return {
            "connected": self._connected,
            "authenticated": self._authenticated,
            "session_authed": self._session_authed,
            "connect_count": self._connect_count,
            "auth_count": self._auth_count,
            "consecutive_reconnect_fails": self._consecutive_reconnect_fails,
            "last_msg_age_sec": (now - self._last_msg_ts
                                  if self._last_msg_ts > 0 else None),
            "last_reconnect_ts": (self._last_reconnect_ts.isoformat()
                                   if self._last_reconnect_ts else None),
            "last_error": self._last_error,
            "subscribed_channels": sorted(self._subscribed_channels),
            "ws_url": self._ws_url(),
            # Per-session breadcrumbs (latest session)
            "last_session": {
                "opened": self._last_session_opened,
                "login_sent": self._last_session_login_sent,
                "msgs_received": self._last_session_msgs_received,
                "last_msg_preview": self._last_session_last_msg,
                "close_code": self._last_session_close_code,
                "close_msg": self._last_session_close_msg,
                "ws_error": self._last_ws_error,
            },
        }

    # ── Internal: connection loop ──────────────────────────────────────

    def _run_loop(self) -> None:
        """Main reconnect loop.  Runs until stop().

        Counter semantics:
          - consecutive_reconnect_fails counts SESSIONS that died WITHOUT
            ever reaching successful auth.  A session that auth'd, ran,
            then closed normally does NOT increment (that's a normal
            OKX-side keepalive cycle, not a failure).
        """
        attempt = 0
        while not self._stop_evt.is_set():
            self._connect_count += 1
            self._session_authed = False    # reset per-session
            self._last_session_opened = False
            self._last_session_login_sent = False
            self._last_session_msgs_received = 0
            self._last_session_close_code = None
            self._last_session_close_msg = None
            self._last_session_last_msg = None
            self._last_ws_error = None
            try:
                logger.info("okx_ws_connecting attempt=%d", attempt)
                self._connect_once()
                # _connect_once returned → session ended.  If we never
                # auth'd this session, count as a fail; otherwise treat
                # the close as benign and reset the consecutive counter.
                if self._session_authed:
                    self._consecutive_reconnect_fails = 0
                else:
                    self._consecutive_reconnect_fails += 1
                    self._last_error = "session_ended_without_auth"
            except Exception as e:
                logger.warning("okx_ws_connect_failed attempt=%d err=%s",
                               attempt, e)
                self._consecutive_reconnect_fails += 1
                self._last_error = f"connect_exception: {type(e).__name__}: {e}"

            if self._stop_evt.is_set():
                break

            # Backoff
            delay_idx = min(attempt, len(self.BACKOFF_SEC) - 1)
            delay = self.BACKOFF_SEC[delay_idx]
            logger.info("okx_ws_reconnecting in %ds (fails=%d)",
                        delay, self._consecutive_reconnect_fails)
            self._last_reconnect_ts = datetime.now(tz=timezone.utc)
            time.sleep(delay)
            attempt += 1

    def _ws_url(self) -> str:
        """Return the WS URL to connect to.

        OKX testnet (demo trading) uses a different host:
            wss://wspap.okx.com:8443/ws/v5/private
        per https://www.okx.com/docs-v5/en/#overview-demo-trading-services
        Live keeps the configured ws_private value.
        """
        if self._cfg.is_simulated == 1:
            return "wss://wspap.okx.com:8443/ws/v5/private"
        return self._cfg.ws_private

    def _connect_once(self) -> None:
        """Blocks until WS closes."""
        url = self._ws_url()

        def on_open(ws):
            with self._lock:
                self._connected = True
                self._last_session_opened = True
                self._last_msg_ts = time.time()
            logger.info("okx_ws_opened")
            # Authenticate
            self._send_auth(ws)

        def on_message(ws, raw_msg: str):
            self._last_msg_ts = time.time()
            self._last_session_msgs_received += 1
            self._last_session_last_msg = (raw_msg or "")[:200]
            try:
                self._handle_message(raw_msg)
            except Exception:
                # P1: never crash WS thread on a single bad message.
                logger.exception("okx_ws_message_handler_failed")

        def on_error(ws, err):
            logger.warning("okx_ws_error err=%s", err)
            self._last_ws_error = f"{type(err).__name__}: {err}"

        def on_close(ws, code, msg):
            with self._lock:
                self._connected = False
                self._authenticated = False
                self._last_session_close_code = code
                self._last_session_close_msg = (str(msg)[:200]
                                                  if msg else None)
            logger.warning("okx_ws_closed code=%s msg=%s", code, msg)

        self._ws = websocket.WebSocketApp(
            url, on_open=on_open, on_message=on_message,
            on_error=on_error, on_close=on_close,
        )
        # run_forever blocks; ping_interval set for auto WS ping frames
        # (separate from OKX-app-level ping)
        self._ws.run_forever(ping_interval=20, ping_timeout=10)

    # ── Internal: auth + subscribe ─────────────────────────────────────

    def _send_auth(self, ws) -> None:
        """OKX private WS login message.

        Sign(ts + 'GET' + '/users/self/verify') with api_secret, base64.
        """
        ts = str(int(time.time()))
        msg = f"{ts}GET/users/self/verify".encode()
        secret = self._cfg.api_secret.encode()
        sign = base64.b64encode(
            hmac.new(secret, msg, hashlib.sha256).digest()
        ).decode()
        login = {
            "op": "login",
            "args": [{
                "apiKey": self._cfg.api_key,
                "passphrase": self._cfg.passphrase,
                "timestamp": ts,
                "sign": sign,
            }],
        }
        try:
            ws.send(json.dumps(login))
            self._last_session_login_sent = True
            logger.info("okx_ws_login_sent")
        except Exception as e:
            logger.exception("okx_ws_login_send_failed")
            self._last_ws_error = f"login_send_exc: {e}"

    def _try_subscribe(self, channels: list[str]) -> None:
        """Send a subscribe message if currently connected + authenticated.

        If not, channels are remembered and re-sent after auth completes.
        """
        if not (self._connected and self._authenticated):
            return
        try:
            args = []
            for ch in channels:
                arg: dict = {"channel": ch}
                if ch in ("positions", "orders"):
                    arg["instType"] = "SWAP"
                args.append(arg)
            payload = {"op": "subscribe", "args": args}
            if self._ws is not None:
                self._ws.send(json.dumps(payload))
                logger.info("okx_ws_subscribed channels=%s", channels)
        except Exception:
            logger.exception("okx_ws_subscribe_failed")

    # ── Internal: message dispatch ─────────────────────────────────────

    def _handle_message(self, raw: str) -> None:
        # OKX heartbeat frames are plain text, not JSON ("pong" replies /
        # empty keepalives). Expected traffic — skip BEFORE json.loads,
        # otherwise every heartbeat logs a full JSONDecodeError traceback
        # (live 2026-07-18: ~130 tracebacks/15min drowning the log stream).
        # Genuine garbage still raises so on_message logs it.
        stripped = raw.strip() if raw else ""
        if not stripped or stripped in ("ping", "pong"):
            return
        msg = json.loads(raw)
        # Auth response
        if msg.get("event") == "login":
            if msg.get("code") == "0":
                self._authenticated = True
                self._session_authed = True
                self._auth_count += 1
                self._consecutive_reconnect_fails = 0
                logger.info("okx_ws_authenticated")
                # Re-subscribe everything we knew about
                if self._subscribed_channels:
                    self._try_subscribe(list(self._subscribed_channels))
            else:
                logger.error("okx_ws_login_failed msg=%s", msg)
                self._last_error = f"login_failed: {msg}"
            return

        # Subscribe ack
        if msg.get("event") == "subscribe":
            return

        # Pong
        if msg.get("event") == "pong" or msg == "pong":
            return

        # Data push
        arg = msg.get("arg", {})
        channel = arg.get("channel")
        data = msg.get("data", [])

        if channel == "orders":
            for item in data:
                evt = _parse_order_event(item)
                if self._on_order is not None:
                    try:
                        self._on_order(evt)
                    except Exception:
                        logger.exception("on_order_callback_failed")

        elif channel == "positions":
            for item in data:
                evt = _parse_position_event(item)
                if self._on_position is not None:
                    try:
                        self._on_position(evt)
                    except Exception:
                        logger.exception("on_position_callback_failed")

        elif channel == "account":
            for item in data:
                evt = _parse_balance_event(item)
                if self._on_balance is not None:
                    try:
                        self._on_balance(evt)
                    except Exception:
                        logger.exception("on_balance_callback_failed")

    # ── Internal: manual ping loop ─────────────────────────────────────

    def _ping_loop(self) -> None:
        """OKX server times out client after 30s of silence.  Send ping
        every 25s to keep alive (only when connected)."""
        while not self._stop_evt.is_set():
            time.sleep(self.PING_INTERVAL_SEC)
            with self._lock:
                ws = self._ws
                connected = self._connected
            if not connected or ws is None:
                continue
            try:
                ws.send("ping")
            except Exception:
                logger.warning("okx_ws_ping_failed", exc_info=True)
